version: '3.8'

services:
  mongo:
    image: mongo:7.0
    container_name: campusbite_mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - campusbite_net

  menu-service:
    build:
      context: ./menu-service
    container_name: campusbite_menu
    ports:
      - "8001:8001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${MENU_MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGINS=${CORS_ORIGINS}
    networks:
      - campusbite_net

  order-service:
    build:
      context: ./order-service
    container_name: campusbite_orders
    ports:
      - "8002:8002"
    depends_on:
      - mongo
      - menu-service
      - notify-service
    environment:
      - MONGO_URI=${ORDER_MONGO_URI}
      - MENU_SERVICE_URL=${MENU_SERVICE_URL}
      - NOTIFY_SERVICE_URL=${NOTIFY_SERVICE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGINS=${CORS_ORIGINS}
    networks:
      - campusbite_net

  notify-service:
    build:
      context: ./notify-service
    container_name: campusbite_notify
    ports:
      - "8003:8003"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${NOTIFY_MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGINS=${CORS_ORIGINS}
    networks:
      - campusbite_net

  auth-service:
    build:
      context: ./auth-service
    container_name: campusbite_auth
    ports:
      - "8004:8004"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${AUTH_MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGINS=${CORS_ORIGINS}
    networks:
      - campusbite_net

  frontend:
    build:
      context: ./frontend
      args:
        VITE_MENU_API_URL: ${VITE_MENU_API_URL}
        VITE_ORDER_API_URL: ${VITE_ORDER_API_URL}
        VITE_NOTIFY_API_URL: ${VITE_NOTIFY_API_URL}
        VITE_AUTH_API_URL: ${VITE_AUTH_API_URL}
    container_name: campusbite_frontend
    ports:
      - "5173:5173"
    depends_on:
      - menu-service
      - order-service
      - notify-service
      - auth-service
    networks:
      - campusbite_net

volumes:
  mongo_data:

networks:
  campusbite_net:
    driver: bridge
