services:
  - type: web
    name: campusbite-menu
    runtime: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    dockerfilePath: ./menu-service/Dockerfile
    dockerContext: ./menu-service
    envVars:
      - fromGroup: campusbite-shared
      - key: MONGO_URI
        sync: false

  - type: web
    name: campusbite-order
    runtime: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    dockerfilePath: ./order-service/Dockerfile
    dockerContext: ./order-service
    envVars:
      - fromGroup: campusbite-shared
      - key: MONGO_URI
        sync: false
      - key: MENU_SERVICE_URL
        fromService:
          name: campusbite-menu
          type: web
          envVarKey: RENDER_EXTERNAL_URL
      - key: NOTIFY_SERVICE_URL
        fromService:
          name: campusbite-notify
          type: web
          envVarKey: RENDER_EXTERNAL_URL

  - type: web
    name: campusbite-notify
    runtime: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    dockerfilePath: ./notify-service/Dockerfile
    dockerContext: ./notify-service
    envVars:
      - fromGroup: campusbite-shared
      - key: MONGO_URI
        sync: false

  - type: web
    name: campusbite-auth
    runtime: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    dockerfilePath: ./auth-service/Dockerfile
    dockerContext: ./auth-service
    envVars:
      - fromGroup: campusbite-shared
      - key: MONGO_URI
        sync: false

  - type: web
    name: campusbite-frontend
    runtime: static
    plan: free
    autoDeploy: true
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_MENU_API_URL
        fromService:
          name: campusbite-menu
          type: web
          envVarKey: RENDER_EXTERNAL_URL
      - key: VITE_ORDER_API_URL
        fromService:
          name: campusbite-order
          type: web
          envVarKey: RENDER_EXTERNAL_URL
      - key: VITE_NOTIFY_API_URL
        fromService:
          name: campusbite-notify
          type: web
          envVarKey: RENDER_EXTERNAL_URL
      - key: VITE_AUTH_API_URL
        fromService:
          name: campusbite-auth
          type: web
          envVarKey: RENDER_EXTERNAL_URL

envVarGroups:
  - name: campusbite-shared
    envVars:
      - key: JWT_SECRET
        generateValue: true
