apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app.kubernetes.io/part-of: campusbite
    app.kubernetes.io/component: auth
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: auth
  ports:
    - name: http
      port: 8004
      targetPort: 8004
